
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.62
distribution_type: module
version: 0.05
name: File-LocalizeNewlines
author: Adam Kennedy <cpan@ali.as>
license: perl
build_requires: 
  Test::More: 0.42
requires: 
  File::Find::Rule: 0.20
  Getopt::Long: 0
  perl: 5.005
  Params::Util: 0.10
  Class::Default: 1.0
  File::Spec: 0.80
  FileHandle: 0
  File::Slurp: 9999.04
abstract: Localize the newlines for one or more files
