name: File-LocalizeNewlines
version: 0.02
abstract: Localize the newlines for one or more files
author: Adam Kennedy<cpan@ali.as>
license: perl
distribution_type: module
build_requires:
  Test::More: 0.47
  File::Spec: 0.82
requires:
  perl: 5.005
  Class::Default: 1.0
  File::Find::Rule: 0.20
  File::Slurp: 9999.04
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
